### PR TITLE
Upgrade ShellCheck to 0.4.7

### LINKED ISSUE #143: Build failure with ShellCheck 0.4.7
- [x] This is a bug report
- [ ] This is a feature request
- [ ] I searched existing issues before opening this one

### Expected behavior

A successful hadolint 1.2.4 build with ShellCheck 0.4.7.

### Actual behavior

A failed build.

### Steps to reproduce the behavior

brew pull https://github.com/Homebrew/homebrew-core/pull/21831
brew install -dvs hadolint

Full build log: https://gist.github.com/ilovezfs/4b4ca3d209780585d704c1636bf0d778

The problem does not occur with ShellCheck 0.4.6.

The error is

```
Failed to install hadolint-1.2.3
Build log ( /private/tmp/hadolint-20171217-99291-1437fs3/hadolint-1.2.4/.cabal-sandbox/logs/ghc-8.2.2/hadolint-1.2.3-Jp4PH93kGpG51V3rMmG4HI.log ):
cabal: Entering directory '.'
Configuring hadolint-1.2.3...
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Preprocessing library for hadolint-1.2.3..
Building library for hadolint-1.2.3..
[1 of 3] Compiling Hadolint.Bash    ( src/Hadolint/Bash.hs, dist/dist-sandbox-f3f6770f/build/Hadolint/Bash.o )

src/Hadolint/Bash.hs:8:81: error:
    • Couldn't match expected type ‘CheckSpec’
                  with actual type ‘Maybe Shell -> CheckSpec’
    • Probable cause: ‘spec’ is applied to too few arguments
      In the second argument of ‘checkScript’, namely ‘spec’
      In the second argument of ‘($)’, namely ‘checkScript si spec’
      In the second argument of ‘($)’, namely
        ‘runIdentity $ checkScript si spec’
  |
8 | shellcheck bashScript = map comment $ crComments $ runIdentity $ checkScript si spec
  |                                                                                 ^^^^

src/Hadolint/Bash.hs:12:38: error:
    • Couldn't match expected type ‘Bool’ with actual type ‘[a0]’
    • In the third argument of ‘CheckSpec’, namely ‘exclusions’
      In the expression: CheckSpec filename script exclusions (Just Bash)
      In an equation for ‘spec’:
          spec = CheckSpec filename script exclusions (Just Bash)
   |
12 |     spec = CheckSpec filename script exclusions (Just Bash)
   |                                      ^^^^^^^^^^

src/Hadolint/Bash.hs:12:50: error:
    • Couldn't match expected type ‘[Integer]’
                  with actual type ‘Maybe Shell’
    • In the fourth argument of ‘CheckSpec’, namely ‘(Just Bash)’
      In the expression: CheckSpec filename script exclusions (Just Bash)
      In an equation for ‘spec’:
          spec = CheckSpec filename script exclusions (Just Bash)
   |
12 |     spec = CheckSpec filename script exclusions (Just Bash)
   |                                                  ^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
hadolint-1.2.3-Jp4PH93kGpG51V3rMmG4HI failed during the building phase. The
exception was:
ExitFailure 1
```

### PR DESCRIPTION
**Pull request by zemanlx**
### What I did
Upgraded ShellCheck to 0.4.7 which is adding `--check-sourced` option and changing the type of [CheckSpec](https://github.com/koalaman/shellcheck/commit/8dd40efb440db9ad189ed49695550596ed20100b#diff-6369a4e9c22ed3b4605c0454805c6e5fR36) to support it.

Fixes #143.
 
### How I did it

The new version is not in LTS stack, therefore, I have had to specify it explicitly in `stack.yaml`. I have set `sourced` to `False` as this is default in ShellCheck and we are not sourcing.

### How to verify it

`stack test` as usual.

### CODE REVIEW

**Comment by lorenzo** [comment]
Nice!
